version: "3"

networks:
  app_network:
    driver: bridge

services:
  web:
    container_name: dayz-community-template-web
    build:
      context: .
      dockerfile: ./Dockerfile
    restart: always
    ports:
      - 3000:3000
    networks:
      - app_network
    env_file:
      - .env.local
    volumes:
      - ./config.ts:/app/config.ts
